csrutil authenticated-root disable;
diskutil mount /Volumes/Mac\ OSX;
 Mount -uv /Volumes/Mac\ OSX;	
 cd /Volumes/Mac\ OSX/System/Library/LaunchAgents;
mkdir tmp;
mv com.apple.ManagedClientAgent.* tmp/;
mv com.apple.mdmclient.* tmp/;
cd ../LaunchDaemons;
mkdir tmp;
mv com.apple.ManagedClient.* tmp/;
mv com.apple.mdmclient.* tmp/;
bless --folder /Volumes/Mac\ OSX/System/Library/CoreServices --bootefi --create-snapshot;
